<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dave_worlds</name>
  <version>3.1.1</version>
  <description>The dave_worlds package</description>
  <author email="dtdavi1@nps.edu">dtdavis</author>
  <maintainer email="dtdavi1@nps.edu">dtdavis</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>uuv_sensor_ros_plugins</exec_depend>
  <exec_depend>ds_sim</exec_depend>

  <export>
    <gazebo_ros gazebo_media_path="${prefix}/worlds"/>
    <gazebo_ros gazebo_media_path="${prefix}/media"/>
  </export>
</package>
